config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'food#index'


resources :food 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
    validates_presence_of :name, :category

    def self.oldest_to_newest
        order(expiration_date: :asc)
        
    end

    def self.alphabetically_asc
       order(name: :asc) 
    end

    def self.category_asc
        order(category: :asc, name: :asc)
    end

    # def self.expiration_asc
    #     # require 'pry'; binding.pry
    #     order(expiration_date: :asc)
    # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
    def index
        # @food = Food.all
        if params[:sort] == "alphabetize_asc"
            @food = Food.all.alphabetically_asc
        elsif params[:sort] == "category_asc"
            @food = Food.all.category_asc
        else
            @food = Food.all
        end
    end

    def new
    end

    def create
        food = Food.new(food_params)
        if food.save
            redirect_to "/"
            flash[:message] = "Your New Food has been Added!"
        else
            flash[:alert] = "Please fill out all fields"
            redirect_to "/food/new"
        end
    end

    def edit
        @food = Food.find(params[:id])
    end

    def update
        food = Food.find(params[:id])
        food.update(food_params)
        if food.save
            flash[:message] = "Your Edit has been Successful!"
            redirect_to root_path
        else
            redirect_to edit_food_path(food.id)
            flash[:alert] = "Please fill out all fields"
        end
    end

    def destroy
        food = Food.find(params[:id])
        food.destroy
        redirect_to root_path
    end

private
    def food_params
        params.permit(:name, :category, :expiration_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/food/edit.html.erb
<%= form_with url: "/food/#{@food.id}", method: :patch, local: true do |form| %>
    <p><%= form.label :name, "Foods Name" %></p>
    <%= form.text_field :name, :value => @food.name %>
    <p><%= form.label :category, "Type Category of Food" %></p>
    <%= form.text_field :category, :value => @food.category %>
    <p><%= form.label :expiration_date, "Select Food's Expiration Date" %></p>
    <%= form.date_field :expiration_date, :expiration_date => @food.expiration_date %>
    <p><%= form.submit "Submit" %></p>
<% end %>

app/views/food/index.html.erb
<div>
<h1> Food Tracker <h1>
<h3><%= link_to "Add Food", "/food/new", method: :get %> </h3>

<table class="table table-bordered table-striped">
  <thead class ="thead-dark">
    <tr>
      <th scope="col">Name
      <%= link_to "A-Z", sort: "alphabetize_asc" %></th>
      <th scope="col">Category
      <%= link_to "Sort", sort: "category_asc" %></th>
      <th scope="col">Expiration Date
      <%= link_to "Date Sort", sort: "expiration_date_asc" %></th>
      <th scope="col">Edit Food</th>
      <th scope="col">Delete Food</th>
    </tr>
  </thead>
  <tbody>
    <% @food.oldest_to_newest.each do |item|%>
    <tr>
      <th scope="row"><%= item.name %></th>
      <td><%= item.category %></td>
        <% if item.expiration_date.blank? %>
          <td><%= item.expiration_date %></td>
          <td><%= link_to "Edit #{item.name}", edit_food_path(item.id) %></td>
          <td><%= link_to "Delete #{item.name}", food_path(item.id), method: :delete %></td>
        <% elsif Date.today.to_s > item.expiration_date  %>
          <td style="background-color:Red;"><%= item.expiration_date %></td>
          <td><%= link_to "Edit #{item.name}", edit_food_path(item.id) %></td>
          <td><%= link_to "Delete #{item.name}", food_path(item.id), method: :delete %></td>
        <% elsif (Date.today + 7).to_s > item.expiration_date %>
          <td style="background-color:Yellow;"><%= item.expiration_date %></td>
          <td><%= link_to "Edit #{item.name}", edit_food_path(item.id) %></td>
          <td><%= link_to "Delete #{item.name}", food_path(item.id), method: :delete %></td>
        <% else %>
          <td style="background-color:Green;"><%= item.expiration_date %></td>
          <td><%= link_to "Edit #{item.name}", edit_food_path(item.id) %></td>
          <td><%= link_to "Delete #{item.name}", food_path(item.id), method: :delete %></td>
    </tr>
    <% end %> 
    <% end %>
  </tbody>
</table>
</div>

app/views/food/new.html.erb
<% flash.each do |type, msg| %>
  <div>
   <h2> <%= msg %> </h2>
  </div>
<% end %>

<%= form_with url: "/food", method: :post, local: true do |form| %>
    <p><%= form.label :name, "Foods Name" %></p>
    <%= form.text_field :name %>
    <p><%= form.label :category, "Type Category of Food" %></p>
    <%= form.text_field :category %>
    <p><%= form.label :expiration_date, "Select Food's Expiration Date" %></p>
    <%= form.date_field :expiration_date %>
    <p><%= form.label :brand, "Brand of Food Item" %></p>
    <%= form.text_field :brand %>
    <p><%= form.label :location, "Where is it located in your kitchen?" %></p>
    <%= form.text_field :location %>
    <p><%= form.submit "Submit" %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<style>
    div{
        padding-left:25px;
    }
</style>
  <head>
    <title>FoodTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |type, msg| %>
      <div>
        <h2> <%= msg %> </h2>
      </div>
    <% end %>
  </body>
</html>